image:
  file: .gitpod.Dockerfile

# This will expose all necessary ports needed for your VNC image
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore

# This will make it so that on workspace start it will run a file called `app.py`
tasks:
  - command: openscad
    init: true
    openMode: split-right
    root: true
# Install all the necessary openSCAD libraries from GitHub... But first, get to know where they're store under Linux.
# How exciting this will be!